/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CUMT.ISAC.WC.TEST;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;

import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.TreePath;

/**
 *
 * @author WangCong
 */
public class mainFrame extends javax.swing.JFrame {

	/**
	 * Creates new form mainFrame
	 */
	public mainFrame() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		moveForward_Button = new javax.swing.JButton();
		moveBackward_Button = new javax.swing.JButton();
		moveStop_Button = new javax.swing.JButton();
		Label11 = new javax.swing.JLabel();
		text_showValue9 = new javax.swing.JTextField();
		Label14 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTree1 = new javax.swing.JTree();
		jPanel2 = new javax.swing.JPanel();
		Label4 = new javax.swing.JLabel();
		Label1 = new javax.swing.JLabel();
		text_showValue4 = new javax.swing.JTextField();
		Label2 = new javax.swing.JLabel();
		Label3 = new javax.swing.JLabel();
		text_showValue1 = new javax.swing.JTextField();
		text_showValue2 = new javax.swing.JTextField();
		text_showValue3 = new javax.swing.JTextField();
		Label5 = new javax.swing.JLabel();
		jPanel3 = new javax.swing.JPanel();
		Label6 = new javax.swing.JLabel();
		Label7 = new javax.swing.JLabel();
		text_showValue5 = new javax.swing.JTextField();
		Label8 = new javax.swing.JLabel();
		Label9 = new javax.swing.JLabel();
		text_showValue6 = new javax.swing.JTextField();
		text_showValue7 = new javax.swing.JTextField();
		text_showValue8 = new javax.swing.JTextField();
		Label10 = new javax.swing.JLabel();
		jPanel4 = new javax.swing.JPanel();
		Label12 = new javax.swing.JLabel();
		text_showValue10 = new javax.swing.JTextField();
		Label15 = new javax.swing.JLabel();
		jPanel5 = new javax.swing.JPanel();
		Label13 = new javax.swing.JLabel();
		text_showValue11 = new javax.swing.JTextField();
		Label16 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setBackground(java.awt.Color.white);

		moveForward_Button.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
		moveForward_Button.setText("正向运动");
		moveForward_Button.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				moveForward_ButtonActionPerformed(evt);
			}
		});

		moveBackward_Button.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
		moveBackward_Button.setText("反向运动");
		moveBackward_Button.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				moveBackward_ButtonActionPerformed(evt);
			}
		});

		moveStop_Button.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
		moveStop_Button.setText("停止运动");
		moveStop_Button.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				moveStop_ButtonActionPerformed(evt);
			}
		});

		Label11.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
		Label11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		Label11.setText("电机控制");

		text_showValue9.setEditable(false);
		text_showValue9.setBackground(new java.awt.Color(255, 255, 255));
		text_showValue9.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
		text_showValue9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		text_showValue9.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

		Label14.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
		Label14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		Label14.setText("速度值");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(89, 89, 89)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addComponent(Label14, javax.swing.GroupLayout.PREFERRED_SIZE, 79,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(text_showValue9, javax.swing.GroupLayout.PREFERRED_SIZE, 80,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addComponent(moveForward_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 133,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18)
										.addComponent(moveBackward_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 133,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18).addComponent(moveStop_Button,
												javax.swing.GroupLayout.PREFERRED_SIZE, 133,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addComponent(Label11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
								.addComponent(Label11, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(text_showValue9, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(Label14, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(24, 24, 24)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(moveStop_Button).addComponent(moveForward_Button)
										.addComponent(moveBackward_Button))
								.addContainerGap()));

		javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("文件列表");
		javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("视频");
		javax.swing.tree.DefaultMutableTreeNode treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("test.mp4");
		treeNode2.add(treeNode4);
		javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("001.mp4");
		treeNode2.add(treeNode3);
		treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("002.wav");
		treeNode2.add(treeNode3);
		treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("003.mp4");
		treeNode2.add(treeNode3);
		treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("004.mp4");
		treeNode2.add(treeNode3);
		treeNode1.add(treeNode2);
		treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("对比结果");
		treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("001.jpg");
		treeNode2.add(treeNode3);
		treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("002.jpg");
		treeNode2.add(treeNode3);
		treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("003.jpg");
		treeNode2.add(treeNode3);
		treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("004");
		treeNode2.add(treeNode3);
		treeNode1.add(treeNode2);
		jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
		jScrollPane1.setViewportView(jTree1);

		jTree1.addTreeSelectionListener(new TreeSelectionListener() {

			@Override
			public void valueChanged(TreeSelectionEvent e) {
				DefaultMutableTreeNode node = (DefaultMutableTreeNode) jTree1.getLastSelectedPathComponent();
				if (node == null) {
					return;
				}
				if (node.toString().equals("test.mp4")) {
					ProcessBuilder process = new ProcessBuilder("F:\\QQ影音\\QQPlayer.exe",
							"F:\\JavaSE_workspace\\MediaPlayer\\001.mp4");
					try {
						process.start();
					} catch (IOException e1) {
						e1.printStackTrace();
					}
				}
			}
		});

		jTree1.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				// 如果在这棵树上点击了2次,即双击
				if (e.getSource() == jTree1 && e.getClickCount() == 2) {
					// 按照鼠标点击的坐标点获取路径
					TreePath selPath = jTree1.getPathForLocation(e.getX(), e.getY());
					if (selPath != null)// 谨防空指针异常!双击空白处是会这样
					{
//                        System.out.println(selPath);// 输出路径看一下
						// 获取这个路径上的最后一个组件,也就是双击的地方
						DefaultMutableTreeNode node = (DefaultMutableTreeNode) selPath.getLastPathComponent();
						if (node.toString().endsWith("jpg")) {
							ProcessBuilder process = new ProcessBuilder("D:\\Fastpic\\fastpic.exe",
									"F:\\JavaSE_workspace\\MediaPlayer\\" + node.toString());
							try {
								process.start();
							} catch (IOException e1) {
								e1.printStackTrace();
							}
						} else {
							ProcessBuilder process = new ProcessBuilder("F:\\QQ影音\\QQPlayer.exe",
									"F:\\JavaSE_workspace\\MediaPlayer\\" + node.toString());
							try {
								process.start();
							} catch (IOException e1) {
								e1.printStackTrace();
							}
//							System.out.println(node.toString());// 输出这个组件toString()的字符串看一下
						}
					}
				}
			}
		});

		jPanel2.setBackground(java.awt.Color.white);

		Label4.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
		Label4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		Label4.setText("温度量");

		Label1.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
		Label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		Label1.setText("瞬时流量");

		text_showValue4.setEditable(false);
		text_showValue4.setBackground(new java.awt.Color(255, 255, 255));
		text_showValue4.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
		text_showValue4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		text_showValue4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

		Label2.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
		Label2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		Label2.setText("累计流量");

		Label3.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
		Label3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		Label3.setText("负压量");

		text_showValue1.setEditable(false);
		text_showValue1.setBackground(new java.awt.Color(255, 255, 255));
		text_showValue1.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
		text_showValue1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		text_showValue1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

		text_showValue2.setEditable(false);
		text_showValue2.setBackground(new java.awt.Color(255, 255, 255));
		text_showValue2.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
		text_showValue2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		text_showValue2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

		text_showValue3.setEditable(false);
		text_showValue3.setBackground(new java.awt.Color(255, 255, 255));
		text_showValue3.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
		text_showValue3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		text_showValue3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

		Label5.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
		Label5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		Label5.setText("甲烷传感器");
		Label5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		Label5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup()
						.addComponent(Label4, javax.swing.GroupLayout.PREFERRED_SIZE, 79,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(text_showValue4))
				.addGroup(jPanel2Layout.createSequentialGroup()
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(Label3, javax.swing.GroupLayout.PREFERRED_SIZE, 79,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(Label2, javax.swing.GroupLayout.PREFERRED_SIZE, 79,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(text_showValue2, javax.swing.GroupLayout.DEFAULT_SIZE, 80,
										Short.MAX_VALUE)
								.addComponent(text_showValue3)))
				.addGroup(jPanel2Layout.createSequentialGroup()
						.addComponent(Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 79,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(text_showValue1, javax.swing.GroupLayout.PREFERRED_SIZE, 80,
								javax.swing.GroupLayout.PREFERRED_SIZE))
				.addComponent(Label5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE));

		jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL,
				new java.awt.Component[] { text_showValue1, text_showValue2, text_showValue3, text_showValue4 });

		jPanel2Layout
				.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel2Layout.createSequentialGroup()
										.addComponent(Label5, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addGap(43, 43, 43)
										.addGroup(jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(text_showValue1, javax.swing.GroupLayout.PREFERRED_SIZE,
														30, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(12, 12, 12)
										.addGroup(jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(Label2, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(text_showValue2, javax.swing.GroupLayout.PREFERRED_SIZE,
														30, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(Label3, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(text_showValue3, javax.swing.GroupLayout.PREFERRED_SIZE,
														30, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(Label4, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(text_showValue4, javax.swing.GroupLayout.PREFERRED_SIZE,
														30, javax.swing.GroupLayout.PREFERRED_SIZE))));

		jPanel3.setBackground(java.awt.Color.white);

		Label6.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
		Label6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		Label6.setText("温度量");

		Label7.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
		Label7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		Label7.setText("瞬时流量");

		text_showValue5.setEditable(false);
		text_showValue5.setBackground(new java.awt.Color(255, 255, 255));
		text_showValue5.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
		text_showValue5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		text_showValue5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

		Label8.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
		Label8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		Label8.setText("累计流量");

		Label9.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
		Label9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		Label9.setText("负压量");

		text_showValue6.setEditable(false);
		text_showValue6.setBackground(new java.awt.Color(255, 255, 255));
		text_showValue6.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
		text_showValue6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		text_showValue6.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

		text_showValue7.setEditable(false);
		text_showValue7.setBackground(new java.awt.Color(255, 255, 255));
		text_showValue7.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
		text_showValue7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		text_showValue7.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

		text_showValue8.setEditable(false);
		text_showValue8.setBackground(new java.awt.Color(255, 255, 255));
		text_showValue8.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
		text_showValue8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		text_showValue8.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

		Label10.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
		Label10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		Label10.setText("瓦斯传感器");
		Label10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		Label10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup()
						.addComponent(Label6, javax.swing.GroupLayout.PREFERRED_SIZE, 79,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(text_showValue5))
				.addGroup(jPanel3Layout.createSequentialGroup()
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(Label9, javax.swing.GroupLayout.PREFERRED_SIZE, 79,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(Label8, javax.swing.GroupLayout.PREFERRED_SIZE, 79,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(text_showValue7, javax.swing.GroupLayout.DEFAULT_SIZE, 80,
										Short.MAX_VALUE)
								.addComponent(text_showValue8)))
				.addGroup(jPanel3Layout.createSequentialGroup()
						.addComponent(Label7, javax.swing.GroupLayout.PREFERRED_SIZE, 79,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(text_showValue6, javax.swing.GroupLayout.PREFERRED_SIZE, 80,
								javax.swing.GroupLayout.PREFERRED_SIZE))
				.addComponent(Label10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE));
		jPanel3Layout
				.setVerticalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel3Layout.createSequentialGroup()
										.addComponent(Label10, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addGap(43, 43, 43)
										.addGroup(jPanel3Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(Label7, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(text_showValue6, javax.swing.GroupLayout.PREFERRED_SIZE,
														30, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(12, 12, 12)
										.addGroup(jPanel3Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(Label8, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(text_showValue7, javax.swing.GroupLayout.PREFERRED_SIZE,
														30, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(jPanel3Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(Label9, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(text_showValue8, javax.swing.GroupLayout.PREFERRED_SIZE,
														30, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(jPanel3Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(Label6, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(text_showValue5, javax.swing.GroupLayout.PREFERRED_SIZE,
														30, javax.swing.GroupLayout.PREFERRED_SIZE))));

		jPanel4.setBackground(java.awt.Color.white);

		Label12.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
		Label12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		Label12.setText("浓度");

		text_showValue10.setEditable(false);
		text_showValue10.setBackground(new java.awt.Color(255, 255, 255));
		text_showValue10.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
		text_showValue10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		text_showValue10.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

		Label15.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
		Label15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		Label15.setText("烟雾传感器");
		Label15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		Label15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout
				.setHorizontalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(Label15, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(jPanel4Layout.createSequentialGroup()
								.addComponent(Label12, javax.swing.GroupLayout.PREFERRED_SIZE, 79,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(text_showValue10, javax.swing.GroupLayout.PREFERRED_SIZE, 80,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(0, 0, Short.MAX_VALUE)));
		jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
						.addComponent(Label15, javax.swing.GroupLayout.PREFERRED_SIZE, 63,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
						.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(Label12, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(text_showValue10, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap()));

		jPanel5.setBackground(java.awt.Color.white);

		Label13.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
		Label13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		Label13.setText("报警");

		text_showValue11.setEditable(false);
		text_showValue11.setBackground(new java.awt.Color(255, 255, 255));
		text_showValue11.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
		text_showValue11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		text_showValue11.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

		Label16.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
		Label16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		Label16.setText("声光报警器");
		Label16.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		Label16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

		javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
		jPanel5.setLayout(jPanel5Layout);
		jPanel5Layout.setHorizontalGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(Label16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addGroup(jPanel5Layout.createSequentialGroup()
						.addComponent(Label13, javax.swing.GroupLayout.PREFERRED_SIZE, 79,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(text_showValue11, javax.swing.GroupLayout.PREFERRED_SIZE, 80,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 20, Short.MAX_VALUE)));
		jPanel5Layout
				.setVerticalGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
								.addComponent(Label16, javax.swing.GroupLayout.PREFERRED_SIZE, 60,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18)
								.addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(Label13, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(text_showValue11, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addContainerGap()));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup()
				.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(layout.createSequentialGroup()
								.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))))));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addContainerGap()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
						.addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
								.addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
				.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE))
				.addComponent(jScrollPane1));

		pack();
	}// </editor-fold>

	private void moveForward_ButtonActionPerformed(java.awt.event.ActionEvent evt) {
		byte[] moveForward = { (byte) 0xAA, 0x60, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55,
				0x55, (byte) 0x5C, 0x2F };
		wifiTools.send_wifi(moveForward);
//		myTools.printHexString(moveForward);
//		System.out.println(moveForward);
	}

	private void moveBackward_ButtonActionPerformed(java.awt.event.ActionEvent evt) {
		byte[] moveBackward = { (byte) 0xAA, 0x61, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55,
				0x55, (byte) 0x5D, 0x2F };
		wifiTools.send_wifi(moveBackward);
//		myTools.printHexString(moveBackward);
//		System.out.println(moveBackward);
	}

	private void moveStop_ButtonActionPerformed(java.awt.event.ActionEvent evt) {
		byte[] moveStop = { (byte) 0xAA, 0x62, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55,
				(byte) 0x5E, 0x2F };
		wifiTools.send_wifi(moveStop);
//		myTools.printHexString(moveStop);
//		System.out.println(moveStop);
	}

	// Variables declaration - do not modify
	private javax.swing.JLabel Label1;
	private javax.swing.JLabel Label10;
	private javax.swing.JLabel Label11;
	private javax.swing.JLabel Label12;
	private javax.swing.JLabel Label13;
	private javax.swing.JLabel Label14;
	private javax.swing.JLabel Label15;
	private javax.swing.JLabel Label16;
	private javax.swing.JLabel Label2;
	private javax.swing.JLabel Label3;
	private javax.swing.JLabel Label4;
	private javax.swing.JLabel Label5;
	private javax.swing.JLabel Label6;
	private javax.swing.JLabel Label7;
	private javax.swing.JLabel Label8;
	private javax.swing.JLabel Label9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTree jTree1;
	private javax.swing.JButton moveBackward_Button;
	private javax.swing.JButton moveForward_Button;
	private javax.swing.JButton moveStop_Button;
	private javax.swing.JTextField text_showValue1;
	private javax.swing.JTextField text_showValue10;
	private javax.swing.JTextField text_showValue11;
	private javax.swing.JTextField text_showValue2;
	private javax.swing.JTextField text_showValue3;
	private javax.swing.JTextField text_showValue4;
	private javax.swing.JTextField text_showValue5;
	private javax.swing.JTextField text_showValue6;
	private javax.swing.JTextField text_showValue7;
	private javax.swing.JTextField text_showValue8;
	private javax.swing.JTextField text_showValue9;
	// End of variables declaration
}
